import Navigation from '../../components/Navigation'
import { font } from './(with-banner)/font'
import './globals.css'
// import { Space_Grotesk } from 'next/font/google'

// const font = Space_Grotesk({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
  title: 'My Next App with NextJS',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>Create next app</title>
      </head>
      <body className={font.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
